version: '3.5'

services:
  postgres:
    image: postgres:10.6-alpine
    environment:
      POSTGRES_DB: budgetdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"